use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'MCToast_Example' do
  pod 'MCToast', :path => '../'

  target 'MCToast_Tests' do
    inherit! :search_paths

    
  end
end
